### ISSUE TITLE
namespaced templates?

### ISSUE THREAD

**Issue by grzm** [seancorfield/clj-new#18]
One legacy aspect of Leiningen (and boot) templates are that the namespace where templates are defined is under `leiningen.new.*`, such as `leiningen.new.app` or `leiningen.new.plugin`. This makes sense when those templates are part of the Leiningen project. However, it works against typical name spacing conventions when third parties *also* create templates under the `leiningen.new` namespace hierarchy. If I create a template, I'd like it to be able to define it under `com.grzm.*` so as to not collide with other templates. A practical example would be a Fulcro template that I want to define differently than the official Fulcro template maintained by Tony Kay.

From a usage point of view, I think it wouldn't be too cumbersome to call these templates in a namespaced fashion. For example, to create a project using the official Fulcro template:

    cli -A:new new fulcro com.grzm/std-fulcro-app

And to use my custom template:

    cli -A:new:grzm-fulcro new com.grzm.template/fulcro com.grzm/custom-fulcro-app

At one time I worked up something that was backwards compatible with Leiningen and boot templates, and if the idea makes sense, I'll dust it off as a PR.

**Comment by seancorfield** [comment]
There are three separate issues here:

1. The template name is used as the group ID (with an artifact ID of `lein-template`, `boot-template`, or `clj-template`) used to fetch the library from Clojars/Maven.
1. The template name is also used as the relative namespace from `leiningen.new`, `boot.new`, or `clj.new` for the actual code to `require` once the artifact is loaded.
1. The convention of `<template-name>/<tool>-template` is also typically how people find available templates, as well as how the https://clj-templates.com website works.

I'm loathed to break those long-standing conventions because a) it would harm discoverability of templates created with arbitrary group/artifact names and b) would add extra complexity to `clj-new` and introduce a behavior that is not shared with Leiningen or Boot (as well as likely making misuse of `clj-new` harder to detect/report when someone supplies a group/artifact that doesn't actually resolve to a template).

What I believe you _can_ do is provide a dotted-name, such as `com.grzm.fulcro`, so you'd get your custom version as `com.grzm.fulcro/lein-template` and the namespace as `leiningen.new.com.grzm.fulcro` and that would already be compatible with Leiningen/Boot/clj I think?

**Comment by seancorfield** [comment]
This won't actually work because the code that runs the template expects to call a function named the same as the template -- so in the above example, it would want to call `<template-engine>.new.com.grzm.fulcro/com.grzm.fulcro` which is clearly invalid.

Two possibilities come to mind:
* strip the leading segments of the template name to get the function name `fulcro`
* change any `.` in the template name to `-` to get the function name `com-grzm-fulcro`

I'm leaning to the former right now.
