### ISSUE TITLE
Custom git templates: multiple template per repo

### ISSUE THREAD

**Issue by tkjone** [seancorfield/clj-new#20]
First off, thank you for creating this library 🙏 

I was playing with generating my own custom templates and really like the idea of specifying a `:git/url` to save me having to manually clone my template repo. 

I could be wrong, but it does not seem possible to specify multiple templates from inside one repo.  Is this correct?

For example,

I initially created a repo which contains multiple templates like  

- `starter-kit/clj/new/template-1`
- `starter-kit/clj/new/template-2`
- `starter-kit/clj/new/template-3`

Now I would like to be able to do something like:

```bash 
clj -A:new https://github.com/somename/starter-kits/template-1@c1fc0cdf5project-name ...

clj -A:new https://github.com/somename/starter-kits/template-2@c1fc0cdf5project-name ...

clj -A:new https://github.com/somename/starter-kits/template-3@c1fc0cdf5project-name ...
```

But this does not seem to be supported as the expectation is that the repo specified only has 1 template and the name of the repo is also the name of the template.

If this is correct, would it be worth while in your opinion to modify the structure so that a user can have multiple templates in one repo?

> note that I am not suggesting that the solution is to extend the url to allow for `template-*` just that it would be neat to allow multiple templates from 1 repo.

Again, thank you for your work and I look forward to helping in any way I can 👍

**Comment by seancorfield** [comment]
You are correct that the assumption is one repo = one template. `clj-new` treats the git URL just like any other coordinates -- Maven/Clojars, local root -- as something `tools.deps` can resolve to a single library to go on the classpath, and once the classpath has the library on it, the template is directly accessible using standard naming conventions.

`clj-new` supports Leiningen and Boot templates as well as `clj`-templates, so that convention is pretty deeply baked in across all three of those: resolve coordinates -> classpath -> template by name.

That said, `:git/url` supports `:deps/root` so it might be possible at that level to support multiple templates inside a repo but then the parsing machinery needs to be updated to extract that optional piece _and_ modify the template name. I'll take a look.

**Comment by seancorfield** [comment]
@tkjone Please try the latest Git SHA version of clj-new and see if it works as you expect. It's kind of hard to test but I think the `:deps/root` will be correct for these templates.

**Comment by tkjone** [comment]
Hey @seancorfield,

Awesome stuff.  I gave it a try using this demo repo https://github.com/tkjone/new-clojurescript and it seems to work like a dream ❤️

**Comment by seancorfield** [comment]
Thank you! Well, it'll be officially in 0.7.6 so I probably ought to document it better :)

**Comment by seancorfield** [comment]
I think that Git URL is not quite right? Should it be `https://github.com/tkjone/new-clojurescript/create-reagent-app@...`?

**Comment by tkjone** [comment]
Indeed.  Updated the above comment.  Copied and pasted the wrong alias.  Still working 👍
