### ISSUE TITLE
Using wrong template

### ISSUE THREAD

**Issue by OrdoFlammae** [seancorfield/clj-new#40]
I have a template called `clj-app`, which is supposed to generate my default template for a Clojure app. However, when I run
```
clojure -A:new clj-app test-app
```
it generates based off the `app` template, not the `clj-app` template. My template is not installed to Clojars, but is installed to my local maven repository.

Output (using `-v` flag):
```
Output from locating template:

Generating a project called test-app based on the 'app' template.
```

**Comment by seancorfield** [comment]
Probably because this file https://github.com/OrdoFlammae/clj-templates/blob/master/clj-app/src/clj/new/clj_app.clj has the wrong namespace and the same wrong function name. Should be `(ns clj.new.clj-app ...)` and `(defn clj-app ...)` respectively.

Here's how I debugged that:
```
(! 623)-> clojure -A:new https://github.com/OrdoFlammae/clj-templates/clj-app@7ff4ea9c49782c309eaf8153a8dbd7eeb6bfc0d9 ordo/test-app -vvv
Output from locating template:

Execution error (ExceptionInfo) at clj-new.helpers/resolve-template (helpers.clj:170).
Found template clj-app but could not resolve clj.new.clj-app/clj-app within it.

Full report at:
/var/folders/p1/30gnjddx6p193frh670pl8nh0000gn/T/clojure-12391323879271023560.edn

Fri May 08 12:57:54
(sean)-(jobs:0)-(~/clojure)
(! 624)-> 
```
See **could not resolve clj.new.clj-app/clj-app** in the error message.
