### ISSUE TITLE
error messages on mistake in clj-new invocations are  confusing

### ISSUE THREAD

**Issue by behrica** [seancorfield/clj-new#78]
Doing any mistake in the correct syntax for third-party libraries

```
clojure -X:project/new clj-new/create :template clj-py-r-template  :name me/my-app
```

is very confusing.

Each time I use it, I do i wrong first,  and the error message does not tell me anything.

Maybe have a look at those "wrong invocations":

```
clojure -X:project/new clj-new/create :template clj-py-r-template/clj-template  :name me/my-app
clojure -X:project/new clj-new/create :template clj-py-r-templateXX  :name me/my-app
clojure -X:project/new clj-new/create :templat clj-py-r-template  :name me/my-app
clojure -X:project/new clj-new/create :templat clj-py-r-template  :nam me/my-app
clojure -X:project/new clj-new/create :template clj-py-r-template:1.2.0 :name me/my-app
```

It seems to be as well confusing that I can either use :template :name keys or positional parameters.

**Comment by seancorfield** [comment]
There's a lot to unpack here and I think you are perhaps missing some basic understanding of the Clojure CLI options.

In #76 you kept trying to use `clojure -A:project/new ...` but `-A` is intended for starting a REPL (only). When you want to run things, you should either use `-M` for "main" or `-X` for "exec". The alias you're using is:

```clojure
 :project/new
  {:replace-deps {com.github.seancorfield/clj-new {:mvn/version "1.1.331"}}
   :exec-fn      clj-new/create
   :exec-args    {:template lib :name practicalli/playground}
   :main-opts    ["-m" "clj-new.create"]}
```

It is (deliberately) setup so you can use it with either `-M` -- because it has `:main-opts` -- or `-X` -- because it also has `:exec-fn` and `:exec-args`.

In #76 you got it working by, essentially, using `-M` (note: `-A` currently still runs "main" but it will stop doing that at some point) and therefore running `:main-opts` so it was as if you had typed:

```bash
clojure -Sdeps '{:deps {com.github.seancorfield/clj-new {:mvn/version "1.1.331"}}}' -M -m clj-new.create clj-py-r-template me/my-app
```

When you run a "main", it gets everything on the command-line as multiple string arguments -- the signature of the `-main` function is:

```clojure
(defn -main [& args] ; takes zero or more strings
  ...)
```

When you run "exec", it parses the command-line as EDN, as key/value pairs, and builds a hash map and passes that as the single argument to the specified function.

Since the `:project/new` alias includes `:exec-fn clj-new/create`, you can omit the target "exec" function from the invocation so the following would be valid:

```bash
clojure -X:project/new :template clj-py-r-template :name me/my-app
```

There's nothing specific to `clj-new` in any of that -- the Clojure CLI either invokes a `-main` function and passes everything as strings or it invokes a specific function with a single hash map created from key/value pairs read as EDN.

Now let's look at your various cases above:

```bash
(! 721)-> clojure -X:project/new :template clj-py-r-template/clj-template  :name me/my-app

Failed with: Failed to resolve version for clj-py-r-template:lein-template.clj-template:jar:RELEASE: Could not find metadata clj-py-r-template:lein-template.clj-template/maven-metadata.xml in local (/Users/sean/.m2/repository)
Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:171).
Could not load artifact for template: clj-py-r-template/clj-template
	Tried coordinates:
		[clj-py-r-template/boot-template.clj-template "RELEASE"]
		[clj-py-r-template/lein-template.clj-template "RELEASE"]

For more detail, enable verbose logging with :verbose 1, 2, or 3
```

Template names can be qualified symbols so the invocation is "correct" but the template you are requesting just doesn't exist. See https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md for Leiningen's discussion of templates (which `clj-new` tries to fetch if it can't find a `clj-template` on the classpath). The example there asks for the template `us.technomancy/liquid-cool` and explains that is has a group ID of `us.technomancy` and an artifact ID of `lein-template.liquid-cool`. If you ask for `foo-bar` as a template, it maps to `foo-bar/lein-template`.

```bash
(! 722)-> clojure -X:project/new :template clj-py-r-templateXX  :name me/my-app

Failed with: Failed to resolve version for clj-py-r-templateXX:lein-template:jar:RELEASE: Could not find metadata clj-py-r-templateXX:lein-template/maven-metadata.xml in local (/Users/sean/.m2/repository)
Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:171).
Could not load artifact for template: clj-py-r-templateXX
	Tried coordinates:
		[clj-py-r-templateXX/boot-template "RELEASE"]
		[clj-py-r-templateXX/lein-template "RELEASE"]

For more detail, enable verbose logging with :verbose 1, 2, or 3
```

This is similar: the invocation is correct but there's no matching template out there.

```bash
(! 725)-> clojure -X:project/new :templat clj-py-r-template  :name me/my-app
Generating a project called my-app based on the 'lib' template.
The lib template is intended for library projects, not applications.
```

The `:project/new` alias provides default values for `:template` and `:name` so if you omit them on the command-line, they will default to `lib` and `practicalli/playground` respectively (in the `:exec-args`). Again, this is how the Clojure CLI works and isn't specific to `clj-new`. Clojure also has the principle that functions that accept hash maps should accept additional key/value pairs and just pass them along. Between what's in the alias and that idiom, you invoked `clj-create/new` with `{:template 'lib :name 'me/my-app :templat 'clj-py-r-template}` so the "exec" function has the keys it needs and just passes the rest along.

```bash
(! 727)-> clojure -X:project/new clj-new/create :templat clj-py-r-template  :nam me/my-app
Generating a project called playground based on the 'lib' template.
The lib template is intended for library projects, not applications.
```

Very similar to the above: the alias provides the defaults and you passed additional key/value pairs (which are just passed through the call chain).

```bash
(! 729)-> clojure -X:project/new :template clj-py-r-template:1.2.0 :name me/my-app
Exception in thread "DefaultMetadataResolver-0-1" Exception in thread "DefaultMetadataResolver-0-0" Exception in thread "DefaultMetadataResolver-0-2" java.lang.IllegalArgumentException: checksum location must be relative
... stacktrace snipped ...
Execution error (ExceptionInfo) at clj-new.helpers/resolve-remote-template (helpers.clj:171).
Could not load artifact for template: clj-py-r-template:1.2.0
	Tried coordinates:
		[clj-py-r-template:1.2.0/boot-template "RELEASE"]
		[clj-py-r-template:1.2.0/lein-template "RELEASE"]
```

This is a variant of the first two cases where you asked for a template that didn't exist. `clj-py-r-template:1.2.0` is a valid Clojure symbol (even with the `:` in it) and this time the underlying (Maven) library throws an exception that `clj-new` does not recognize as a simple failure to resolve the coordinate so it prints the stacktrace and then explains what it tried.

If you want to use a specific version of a template, you need to pass `:version`, per `clj-new`'s README:

```bash
(! 730)-> clojure -X:project/new :template clj-py-r-template :version '"1.2.0"' :name me/my-app
Generating clj-py-r template for my-app at me/my_app.
```

Since you're passing a string as EDN, it needs the double-quotes to be recognized as a string and the single-quotes so the shell passes the quoted string correctly -- see https://clojure.org/reference/deps_and_cli#quoting

Practicalli is generally aimed more at beginners so it should probably do a better job of explaining the `-M`/`-X` thing especially since it is setting up the aliases to be invoked _both ways_.

If you follow the `clj-new` README https://github.com/seancorfield/clj-new/blob/develop/README.md it avoids the `:main-opts` and `-M` approach altogether (it's considered a legacy style of invocation for `clj-new` and it is no longer documented) so Practicalli should perhaps drop `:main-opts` from the `:project/new` alias?

The recommended usage for `clj-new` is to install it as a "tool" which requires you are using a recent Clojure CLI version. See https://clojure.org/releases/tools for a list -- 1.10.3.933 introduced "tool" support. From the `clj-new` README:

```bash
# do this just once to install clj-new:
clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "v1.1.331"}' :as clj-new

# after installation, you can use the following commands to create new projects:

# create a new app:
clojure -Tclj-new app :name myname/myapp
# create a new library:
clojure -Tclj-new lib :name myname/mylib
# create a new template:
clojure -Tclj-new template :name myname/mytemplate
# create a new project from a public template:
clojure -Tclj-new create :template electron-app :name myname/myelectron-app
```

I hope that helps -- and explains why you are getting the "wrong" results.

**Comment by behrica** [comment]
Yes, at the end it's confusion on my side, so we can close here.

But I use Clojure since years, but each time I want to make a project from a template "something" blocks me.

It has for sure as well todo with the "unusual way"  of the Clojure CLI to handle parameters, where in clj-new we cannot do anything about.

I was thinking that a more explicit "check" for parameters could be thought about for clj-new. I will give it an other try to propose that.
