### ISSUE TITLE
can't create project from template

### ISSUE THREAD

**Issue by TiboGabriels** [seancorfield/clj-new#81]
I'm trying to make a template from this [github](https://github.com/kommen/datahike-heroku) and must say that i am very new to all this, first i was using the creator's [guide](https://nextjournal.com/kommen/datahike-heroku-datalog-clojure-web-app) which i think is slightly outdated.  It gave me this command:
```
clj -X:new create :template '"https://github.com/kommen/datahike-heroku@1ad6b45a6ee49a785f34ba9f12b10db3cae80399"' \ 
:name myorg/testapp
```
`Unreadable arg: "https://github.com/kommen/datahike-heroku@1ad6b45a6ee49a785f34ba9f12b10db3cae80399"`
After looking around on this repo i think this might be right but then i get another error that i do not understand.
```
clj -Tclj-new create :template '"https://github.com/kommen/datahike-heroku"' \ 
:name howest/testapp
```
`Error building classpath. Bad coordinate for library , expected map: nil`

Could someone help me out with this?

**Comment by seancorfield** [comment]
The following command works for me on macOS and Linux (because I have `clj-new` installed as a CLI tool):

```bash
clj -Tclj-new create :template '"https://github.com/kommen/datahike-heroku@1ad6b45a6ee49a785f34ba9f12b10db3cae80399"' :name howest/testapp
```

The following should work for you if you have `:new` as an alias in your `deps.edn` file:

```bash
clj -X:new create :template '"https://github.com/kommen/datahike-heroku@1ad6b45a6ee49a785f34ba9f12b10db3cae80399"' :name howest/testapp
```

If you are on Windows, the quoting rules for the shell are different (but I do not use `cmd` or Powershell so I can't help you with that).

The commands you have above also have an extra space after the `\` which will cause problems.

**Comment by TiboGabriels** [comment]
Thanks i'll try this!
