### ISSUE TITLE
-T no longer supported

### ISSUE THREAD

**Issue by YassinRian** [seancorfield/clj-new#89]
clojure -Tnew scratch :name play
-T is no longer supported, use -A with repl, -M for main, or -X for exec

now what?

**Comment by seancorfield** [comment]
Per the README:
> Note: these instructions assume you are using the Clojure CLI version 1.10.3.933 or later! See Clojure Tools Releases for details about the functionality in recent CLI releases. Projects generated by clj-new also assume at least version 1.10.3.933!

Your `clojure` is likely an old version.

**Comment by YassinRian** [comment]
Thanks for the quick response !

**Comment by seancorfield** [comment]
It can be a bit confusing if you haven't followed the evolution of the CLI closely because there used to be a `-T` option for a different style of "tool" aliases way back (in maybe the 1.10.0 days?) and then it was removed when `-X` was introduced (in 1.10.1.697 -- September 2020) and that's when the "no longer supported" message was added. It stayed like that until the new `-T` option was introduced in 1.10.3.933 (July 2021). Things have been pretty stable since then although recent changes in Clojure (1.12 Alphas) require 1.11.1.1347 (May 31, 2023).

It's a good idea to keep your CLI up-to-date. Releases are listed here with changes: https://clojure.org/releases/tools
